# Browser-side picker for `select_section` / `select_sections`. This JavaScript is
# injected into the rendered filing (see the page builder in Step 1.2). It draws a
# hover highlight, lets the user widen/narrow the selection with the arrow keys, and on
# confirm POSTs the transport payload (schema version 1) back to the local Julia server.
#
# `{{ENDPOINT}}` (the /select POST URL), `{{DONE_ENDPOINT}}` (the /done POST URL),
# `{{MULTI}}` (`true`/`false`) and `{{PROVENANCE}}` (a {cik,accession,url} JSON object)
# are substituted by the page builder. The selector is generated by a compact built-in
# (id, else an :nth-of-type path) — our own code, no third-party dependency. The MIT
# `finder` library could be swapped in later as a more robust replacement (it would then
# need its MIT attribution); it is NOT bundled here. Structured `table` and resolved `facts`
# are added to the payload in Steps 2.1 and 3.1–3.2; v1 sends selector/kind/text/html.

const PICKER_JS = raw"""
(function () {
  "use strict";
  var ENDPOINT = "{{ENDPOINT}}";
  var DONE_ENDPOINT = "{{DONE_ENDPOINT}}";
  var MULTI = {{MULTI}};
  var PROVENANCE = {{PROVENANCE}};

  var current = null;   // element currently highlighted
  var captured = 0;     // how many regions captured so far (multi mode)

  // Compact CSS selector: an id short-circuits, otherwise an :nth-of-type path.
  function cssPath(el) {
    if (el.id) { return "#" + CSS.escape(el.id); }
    var parts = [];
    while (el && el.nodeType === 1 && el !== document.body) {
      if (el.id) { parts.unshift("#" + CSS.escape(el.id)); break; }
      var name = el.nodeName.toLowerCase();
      var nth = 1, sib = el;
      while ((sib = sib.previousElementSibling)) {
        if (sib.nodeName === el.nodeName) { nth++; }
      }
      parts.unshift(name + ":nth-of-type(" + nth + ")");
      el = el.parentElement;
    }
    return parts.join(" > ");
  }

  // :table if it is/contains a table, :prose otherwise.
  function kindOf(el) {
    if (el.tagName === "TABLE") { return "table"; }
    if (el.querySelector && el.querySelector("table")) { return "mixed"; }
    return "prose";
  }

  // The <table> to serialize for a selection: itself if it is one, else the first
  // table inside it (a :mixed wrapper). null for prose.
  function tableOf(el) {
    if (el.tagName === "TABLE") { return el; }
    return el.querySelector ? el.querySelector("table") : null;
  }

  // Serialize a <table> to a rectangular grid of trimmed cell strings, resolving
  // colspan (the text goes in the first spanned column, blanks after) and rowspan
  // (the value is carried down into the columns of the following rows). Returns an
  // array of equal-length string rows — faithfully, including the many empty
  // spacer rows/columns SEC iXBRL tables use for indentation and $ alignment.
  // Pruning empty columns and picking the header row is the renderer's job (2.2).
  function serializeTable(table) {
    var grid = [];
    var pending = {};                 // column -> { text, left } active rowspans
    function drain(row, col) {        // fill columns held by a rowspan from above
      while (pending[col] && pending[col].left > 0) {
        row[col] = pending[col].text;
        if (--pending[col].left === 0) { delete pending[col]; }
        col++;
      }
      return col;
    }
    var trs = table.querySelectorAll("tr");
    for (var i = 0; i < trs.length; i++) {
      var row = [], col = 0, kids = trs[i].children;
      for (var c = 0; c < kids.length; c++) {
        var cell = kids[c];
        if (cell.tagName !== "TD" && cell.tagName !== "TH") { continue; }
        col = drain(row, col);
        var text = (cell.innerText || "").replace(/\s+/g, " ").trim();
        var colspan = parseInt(cell.getAttribute("colspan"), 10) || 1;
        var rowspan = parseInt(cell.getAttribute("rowspan"), 10) || 1;
        for (var k = 0; k < colspan; k++) {
          var v = (k === 0) ? text : "";
          row[col] = v;
          if (rowspan > 1) { pending[col] = { text: v, left: rowspan - 1 }; }
          col++;
        }
      }
      drain(row, col);
      grid.push(row);
    }
    var width = 0, r, w;
    for (r = 0; r < grid.length; r++) { if (grid[r].length > width) { width = grid[r].length; } }
    for (r = 0; r < grid.length; r++) {
      for (w = 0; w < width; w++) { if (grid[r][w] == null) { grid[r][w] = ""; } }
    }
    return grid;
  }

  // A short human summary of what will be captured, for the confirmation toast:
  // rows × cols for a (mixed) table, character count for prose.
  function summarize(el, kind) {
    if (kind === "table" || kind === "mixed") {
      var rows = el.querySelectorAll("tr").length;
      var firstRow = el.querySelector("tr");
      var cols = firstRow ? firstRow.querySelectorAll("td,th").length : 0;
      return rows + " rows" + (cols ? " &times; " + cols + " cols" : "");
    }
    return ((el.innerText || "").trim().length) + " chars";
  }

  // A short synthesised "shutter" click on a successful capture — like the macOS
  // screenshot chonk, but generated with the Web Audio API (no asset needed). The
  // capture is triggered by a key/click, which counts as the user gesture browsers
  // require before audio may play.
  var audioCtx = null;
  function chonk() {
    try {
      audioCtx = audioCtx || new (window.AudioContext || window.webkitAudioContext)();
      if (audioCtx.state === "suspended") { audioCtx.resume(); }
      var t = audioCtx.currentTime;
      var o = audioCtx.createOscillator();
      var g = audioCtx.createGain();
      o.type = "square";
      o.frequency.setValueAtTime(900, t);
      o.frequency.exponentialRampToValueAtTime(170, t + 0.08);
      g.gain.setValueAtTime(0.0001, t);
      g.gain.exponentialRampToValueAtTime(0.22, t + 0.005);
      g.gain.exponentialRampToValueAtTime(0.0001, t + 0.12);
      o.connect(g); g.connect(audioCtx.destination);
      o.start(t); o.stop(t + 0.13);
    } catch (e) { /* audio unavailable — silent is fine */ }
  }

  // ── iXBRL header (Step 3.1) ────────────────────────────────────────────────
  // Parse the inline-XBRL <ix:header> resources into a context map (period, entity,
  // dimensions) and a unit map, keyed by id, so resolving the facts inside a selection
  // (Step 3.2) is a lookup. The browser parses iXBRL as HTML, so the namespaced tags
  // (xbrli:/ix:/xbrldi:) are matched by local name, case-insensitively, ignoring the
  // prefix. Built once and cached; exposed on window for inspection / Step 3.2.

  function localName(el) {
    var n = el.nodeName.toLowerCase(), i = n.indexOf(":");
    return i >= 0 ? n.slice(i + 1) : n;
  }
  function descendantsByLocal(root, local) {
    var all = root.getElementsByTagName("*"), out = [];
    for (var i = 0; i < all.length; i++) {
      if (localName(all[i]) === local) { out.push(all[i]); }
    }
    return out;
  }
  function firstByLocal(root, local) {
    var x = descendantsByLocal(root, local);
    return x.length ? x[0] : null;
  }
  function measureName(el) {                 // <xbrli:measure>iso4217:USD</> -> "USD"
    var m = el && firstByLocal(el, "measure");
    if (!m) { return ""; }
    var t = m.textContent.trim(), i = t.indexOf(":");
    return i >= 0 ? t.slice(i + 1) : t;
  }
  function parseContext(ctx) {
    var period = {};
    var inst = firstByLocal(ctx, "instant");
    if (inst) {
      period.instant = inst.textContent.trim();
    } else {
      var sd = firstByLocal(ctx, "startdate"), ed = firstByLocal(ctx, "enddate");
      if (sd) { period.start = sd.textContent.trim(); }
      if (ed) { period.end = ed.textContent.trim(); }
    }
    var id = firstByLocal(ctx, "identifier");
    var dims = {};
    var ems = descendantsByLocal(ctx, "explicitmember");
    for (var i = 0; i < ems.length; i++) {
      dims[ems[i].getAttribute("dimension") || ""] = ems[i].textContent.trim();
    }
    return { period: period, entity: id ? id.textContent.trim() : "", dimensions: dims };
  }
  function parseUnit(u) {
    var div = firstByLocal(u, "divide");
    if (div) {
      return measureName(firstByLocal(div, "unitnumerator")) + "/" +
             measureName(firstByLocal(div, "unitdenominator"));
    }
    return measureName(u);
  }
  // Top-level <xbrli:context>/<xbrli:unit> by local name. Fast path: the browser
  // indexes getElementsByTagName by qualified name, so the standard `xbrli:` prefix
  // is an indexed lookup; fall back to a full scan only if a filing uses another prefix.
  function topLevelByLocal(local) {
    var fast = document.getElementsByTagName("xbrli:" + local);
    return fast.length ? fast : descendantsByLocal(document, local);
  }
  var _xbrl = null;
  function xbrlMaps() {
    if (_xbrl) { return _xbrl; }
    _xbrl = { contexts: {}, units: {} };
    try {
      var cs = topLevelByLocal("context");
      for (var i = 0; i < cs.length; i++) {
        var cid = cs[i].getAttribute("id"); if (cid) { _xbrl.contexts[cid] = parseContext(cs[i]); }
      }
      var us = topLevelByLocal("unit");
      for (var j = 0; j < us.length; j++) {
        var uid = us[j].getAttribute("id"); if (uid) { _xbrl.units[uid] = parseUnit(us[j]); }
      }
    } catch (e) { /* non-iXBRL or unexpected shape — leave the maps empty */ }
    window.__EDGAR_XBRL = _xbrl;   // exposed for inspection and Step 3.2
    return _xbrl;
  }
  // Build off the critical path so the picker is interactive immediately; capture
  // (Step 3.2) calls xbrlMaps() too, and it is memoised, so the work happens once.
  // Call the scheduler as a method on window (an unbound `setTimeout` reference throws
  // "Illegal invocation" in Chrome), and guard so scheduling can never break the picker.
  try {
    var buildXbrl = function () { try { xbrlMaps(); } catch (e) { /* ignore */ } };
    if (window.requestIdleCallback) { window.requestIdleCallback(buildXbrl); }
    else { window.setTimeout(buildXbrl, 1); }
  } catch (e) { /* ignore */ }

  // ── iXBRL facts in a selection (Step 3.2) ──────────────────────────────────
  // Resolve each numeric tag (<ix:nonFraction>) inside the picked element against the
  // context/unit maps into the fact transport shape. Non-numeric tags (<ix:nonNumeric>)
  // are text, not facts, and are skipped. The raw value text is cleaned to a parseable
  // number — commas/currency dropped, parentheses read as a negative — and the scale,
  // sign and decimals attributes pass through for the Julia side to normalise.
  function factNumber(el, signAttr) {
    var t = (el.textContent || "").replace(/\u00a0/g, " ").trim();
    var neg = signAttr === "-";
    if (/^\(.*\)$/.test(t)) { neg = true; t = t.slice(1, -1); }   // (79) -> 79, negative
    return { value: t.replace(/[^0-9.]/g, ""), sign: neg ? "-" : "" };
  }
  // Best-effort human label: the first non-empty cell of the fact's table row.
  function rowLabel(f) {
    var tr = f.closest ? f.closest("tr") : null;
    if (!tr) { return ""; }
    var cells = tr.querySelectorAll("td, th");
    for (var i = 0; i < cells.length; i++) {
      var t = (cells[i].innerText || cells[i].textContent || "").replace(/\s+/g, " ").trim();
      if (t) { return t; }
    }
    return "";
  }
  function factsIn(el) {
    var maps = xbrlMaps(), out = [];
    var nfs = descendantsByLocal(el, "nonfraction");
    for (var i = 0; i < nfs.length; i++) {
      var f = nfs[i], concept = f.getAttribute("name");
      if (!concept) { continue; }
      var ctxRef = f.getAttribute("contextRef") || "", unitRef = f.getAttribute("unitRef") || "";
      var ctx = maps.contexts[ctxRef];
      if (!ctx) { continue; }
      var p = ctx.period || {}, isInstant = p.instant != null;
      var periodEnd = isInstant ? p.instant : p.end;
      if (!periodEnd) { continue; }                    // need a period end to be a fact
      var num = factNumber(f, f.getAttribute("sign") || "");
      if (!num.value) { continue; }                    // nil / dash / non-numeric — skip
      var decAttr = f.getAttribute("decimals");
      out.push({
        concept: concept,
        label: rowLabel(f),
        value: num.value,
        sign: num.sign,
        scale: parseInt(f.getAttribute("scale"), 10) || 0,
        decimals: (decAttr == null || decAttr === "INF") ? null : parseInt(decAttr, 10),
        unit: maps.units[unitRef] || "",
        unitRef: unitRef,
        contextRef: ctxRef,
        periodStart: isInstant ? null : (p.start || null),
        periodEnd: periodEnd,
        isInstant: isInstant,
        dimensions: ctx.dimensions || {}
      });
    }
    return out;
  }

  // Highlight box (pointer-events:none so it never intercepts the cursor). Its
  // colour reflects what will be captured — see colorFor.
  var box = document.createElement("div");
  box.style.cssText = "position:absolute;z-index:2147483646;pointer-events:none;" +
    "border:3px solid #8957e5;background:rgba(137,87,229,0.18);border-radius:2px;" +
    "transition:background .05s,border-color .05s;";
  document.body.appendChild(box);

  // A small badge pinned to the box's top-left naming the kind, so the feedback
  // is right at the cursor and not only in the toolbar.
  var badge = document.createElement("div");
  badge.style.cssText = "position:absolute;z-index:2147483647;pointer-events:none;" +
    "font:700 11px/1 system-ui,sans-serif;color:#fff;padding:3px 6px;" +
    "border-radius:0 0 4px 0;white-space:nowrap;display:none;";
  document.body.appendChild(badge);

  // Fixed toolbar with instructions and the current tag.
  var bar = document.createElement("div");
  bar.style.cssText = "position:fixed;z-index:2147483647;left:50%;bottom:16px;" +
    "transform:translateX(-50%);background:#1e1e2e;color:#eee;border-radius:8px;" +
    "font:13px/1.4 system-ui,sans-serif;padding:8px 14px;box-shadow:0 4px 16px rgba(0,0,0,.3);";
  bar.innerHTML = MULTI
    ? "EDGAR picker (multi) &mdash; hover, <b>&uarr;/&darr;</b> resize, " +
      "<b>Enter</b>/click to <b>add</b>, <b>Esc</b> to finish &nbsp; <span id='edgar-tag'></span>"
    : "EDGAR picker &mdash; hover a number, press <b>&uarr;</b> until it turns " +
      "<b style='color:#2ea043'>GREEN (TABLE)</b>, then <b>Enter</b> to capture &nbsp;&middot;&nbsp; " +
      "<b>&darr;</b> narrow, <b>Esc</b> cancel &nbsp; <span id='edgar-tag'></span>";
  document.body.appendChild(bar);
  var tagSpan = bar.querySelector("#edgar-tag");

  // Capture-target colour + label by kind: green = a table (what you usually want),
  // amber = a region that contains a table (mixed), purple = prose/text.
  function colorFor(kind) {
    if (kind === "table") { return { line: "#2ea043", fill: "rgba(46,160,67,0.18)", label: "TABLE" }; }
    if (kind === "mixed") { return { line: "#d29922", fill: "rgba(210,153,34,0.18)", label: "TABLE + text" }; }
    return { line: "#8957e5", fill: "rgba(137,87,229,0.18)", label: "text" };
  }

  function highlight(el) {
    if (!el || el === box || el === bar || el === badge || bar.contains(el)) { return; }
    current = el;
    var r = el.getBoundingClientRect();
    box.style.top = (r.top + window.scrollY) + "px";
    box.style.left = (r.left + window.scrollX) + "px";
    box.style.width = r.width + "px";
    box.style.height = r.height + "px";
    var c = colorFor(kindOf(el));
    box.style.borderColor = c.line;
    box.style.background = c.fill;
    badge.style.display = "block";
    badge.style.top = (r.top + window.scrollY) + "px";
    badge.style.left = (r.left + window.scrollX) + "px";
    badge.style.background = c.line;
    badge.textContent = c.label;
    tagSpan.innerHTML = "<b style='color:" + c.line + "'>" + c.label + "</b> &lt;" +
      el.nodeName.toLowerCase() + (el.id ? "#" + el.id : "") + "&gt;";
  }

  function finish(msg) { box.remove(); badge.remove(); bar.innerHTML = msg; }

  // Tell the server we are done (Esc / end of a multi session). Fire-and-forget;
  // keepalive lets it complete even if the tab is closing.
  function sendDone() {
    try {
      fetch(DONE_ENDPOINT, { method: "POST", keepalive: true,
        headers: { "Content-Type": "application/json" }, body: "{}" });
    } catch (e) { /* ignore */ }
  }

  var sending = false;   // guards against a double-send while a POST is in flight

  function capture(el) {
    if (sending) { return; }
    sending = true;
    var kind = kindOf(el);
    tagSpan.textContent = "sending…";
    // Structured table (header + rows) when the selection is/contains a table;
    // null for prose. The Julia side normalises and renders it (Markdown, facts).
    var table = null;
    var tbl = tableOf(el);
    if (tbl) {
      var grid = serializeTable(tbl);
      // Send the faithful grid as rows; the renderer prunes empty columns and
      // promotes the header row (2.2). header is left empty here on purpose.
      if (grid.length) { table = { header: [], rows: grid }; }
    }
    var payload = {
      version: 1,
      provenance: PROVENANCE,
      selector: cssPath(el),
      kind: kind,
      text: el.innerText || "",
      html: el.outerHTML || "",
      table: table,
      facts: factsIn(el)
    };
    fetch(ENDPOINT, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    }).then(function (res) {
      if (!res.ok) { throw new Error("HTTP " + res.status); }
      return res.text();   // the server replies with the running capture count
    }).then(function (countText) {
      chonk();
      var n = parseInt(countText, 10); if (isNaN(n)) { n = captured + 1; }
      captured = n;
      var summary = colorFor(kind).label + " &mdash; " + summarize(el, kind);
      if (MULTI) {
        // Keep the picker alive and report progress; the user picks again or Esc.
        sending = false;
        bar.innerHTML = "&#10003; " + summary + " &nbsp;&middot;&nbsp; <b>" + captured +
          " captured</b> &mdash; keep picking, <b>Esc</b> to finish &nbsp; <span id='edgar-tag'></span>";
        tagSpan = bar.querySelector("#edgar-tag");
      } else {
        finish("&#10003; Captured " + summary + " &mdash; you can close this tab.");
      }
    }).catch(function (err) {
      // A failed send must NOT tear the picker down: keep the highlight box and
      // toolbar alive so the pick can be retried (the server may have timed out).
      sending = false;
      tagSpan.textContent = "✗ send failed (" + err + ") — try again";
    });
  }

  var lastHover = null;   // element under the cursor at the last real move

  document.addEventListener("mousemove", function (e) {
    var el = document.elementFromPoint(e.clientX, e.clientY);
    // React only when the cursor moves to a DIFFERENT element, so widening with
    // the arrow keys is not instantly undone by a stray mousemove — the cursor
    // sitting still over a cell still fires these events. A table is fully
    // covered by its own cells, so reaching the <table> level (green) is only
    // possible via ↑, which this makes stick until you actually move away.
    if (el && el !== lastHover) { lastHover = el; highlight(el); }
  }, true);

  document.addEventListener("keydown", function (e) {
    if (e.key === "ArrowUp" && current && current.parentElement &&
        current.parentElement !== document.body) {
      highlight(current.parentElement); e.preventDefault();
    } else if (e.key === "ArrowDown" && current && current.firstElementChild) {
      highlight(current.firstElementChild); e.preventDefault();
    } else if (e.key === "Enter" && current) {
      capture(current); e.preventDefault();
    } else if (e.key === "Escape") {
      sendDone();
      finish(MULTI
        ? "&#10003; Done &mdash; " + captured + " captured. You can close this tab."
        : "Picker cancelled.");
    }
  }, true);

  // Capture-phase click: intercept (so filing links don't navigate) and confirm.
  document.addEventListener("click", function (e) {
    if (current && !bar.contains(e.target)) {
      e.preventDefault(); e.stopPropagation(); capture(current);
    }
  }, true);
})();
"""

# Build the page served to the browser for picking: the filing's HTML with a `<base>`
# (so its relative images still resolve to the SEC Archives) injected into <head>, and
# the picker script injected before </body> with the /select and /done endpoints, the
# multi-select mode flag, and the filing's provenance substituted in.
function _build_picker_page(f::Filing, origin::AbstractString, multi::Bool)
    prov = JSON3.write((; cik = f.entity.value, accession = f.ref, url = f.url))
    script = "<script>\n" *
             replace(PICKER_JS,
                     "{{ENDPOINT}}" => "$origin/select",
                     "{{DONE_ENDPOINT}}" => "$origin/done",
                     "{{MULTI}}" => multi ? "true" : "false",
                     "{{PROVENANCE}}" => prov) *
             "\n</script>"
    page = f.content
    base = _filing_base_url(f)
    if !isempty(base)
        basetag = "<base href=\"$base\">"
        head = match(r"(?is)<head\b[^>]*>", page)
        page = head === nothing ? basetag * page :
               replace(page, head.match => head.match * basetag; count = 1)
    end
    bc = findlast("</body>", page)
    return bc === nothing ? page * script :
           page[1:prevind(page, first(bc))] * script * page[first(bc):end]
end

# Internal: an OS-assigned free TCP port on the loopback interface. (Tiny race
# between close and re-listen, acceptable for a local, short-lived picker session.)
function _free_port()
    s = Sockets.listen(Sockets.localhost, 0)
    port = Int(Sockets.getsockname(s)[2])
    close(s)
    return port
end

# Internal: start a localhost HTTP server that serves the picker page for `f` and
# receives the selection POSTs. Returns `(server, results, done, finish_once, url)`:
# `results` is the live vector picks are appended to (de-duplicated by selector),
# `done` is signalled (a single `put!`) when the session ends — after the first pick
# in single mode, on a /done POST (Esc) in multi mode, or when the caller's timer
# fires `finish_once`. Bound to 127.0.0.1 only, so nothing is exposed off the machine.
function _start_picker_server(f::Filing; multi::Bool=false)
    port = _free_port()
    url = "http://127.0.0.1:$port/"
    origin = "http://127.0.0.1:$port"
    page = _build_picker_page(f, origin, multi)
    results = Selection[]
    lk = ReentrantLock()
    done = Channel{Nothing}(1)
    finished = Ref(false)
    function finish_once()
        lock(lk) do
            if !finished[]
                finished[] = true
                put!(done, nothing)
            end
        end
    end
    function handler(req::HTTP.Request)
        if req.method == "GET" && (req.target == "/" || startswith(req.target, "/?"))
            return HTTP.Response(200, ["Content-Type" => "text/html; charset=utf-8"], page)
        elseif req.method == "POST" && occursin("/select", req.target)
            try
                sel = parse_selection(String(req.body))
                n = lock(lk) do
                    any(s -> s.selector == sel.selector, results) || push!(results, sel)
                    length(results)
                end
                multi || finish_once()       # single mode finishes on the first pick
                return HTTP.Response(200, string(n))
            catch e
                return HTTP.Response(400, "bad selection payload: $e")
            end
        elseif req.method == "POST" && occursin("/done", req.target)
            finish_once()
            return HTTP.Response(200, "ok")
        end
        return HTTP.Response(404, "not found")
    end
    server = HTTP.serve!(handler, "127.0.0.1", port)
    return (server, results, done, finish_once, url)
end

# Internal: the shared driver behind `select_section` (single) and `select_sections`
# (multi). Serves the page, opens it, blocks until the session ends or `timeout`
# seconds elapse, and returns the collected selections (possibly empty).
function _run_picker(f::Filing; timeout::Real, opener, multi::Bool)
    server, results, done, finish_once, url = _start_picker_server(f; multi)
    timer = Timer(_ -> finish_once(), timeout)   # ends the session if nothing arrives
    try
        opener(url)
        take!(done)                              # unblocks on the first put! / timeout
        return results
    finally
        close(timer)
        close(server)
    end
end

"""
    select_section(f::Filing; timeout=1800, classify=false, opener=_open_in_default_app) -> Selection

Open the filing `f` in your browser with an interactive picker and return the region
you choose as a [`Selection`](@ref). **Hover** to highlight an element, use the
**arrow keys** to widen/narrow to its parent/child, and press **Enter** (or click) to
capture; the region — its text, structured table, and any resolved XBRL facts — is
sent back to Julia. The highlight is colour-coded by what will be captured (green =
a `<table>`, amber = a region containing one, purple = prose); a successful capture
plays a short confirmation sound. Press **Esc** or close the tab to cancel.

To capture several regions in one session, use [`select_sections`](@ref). Preview a
returned `Selection` in the browser with [`open_filing`](@ref).

A local HTTP server bound to `127.0.0.1` serves the page and receives the pick; it is
shut down as soon as a selection arrives or `timeout` seconds elapse. Throws if
nothing is selected within `timeout` (a cancel looks like a timeout). `opener` is the
function used to open the page — the default launches your browser; substitute it
(e.g. for headless testing) to drive the page another way.

With `classify=true`, each picked fact's `statement` (`IncomeStatement`, `BalanceSheet`, …)
is filled from the filing's presentation linkbase (see [`statement_map`](@ref)), the same
authoritative source as `facts(::Filing; classify=true)` — one extra fetch of the `*_pre.xml`.

```julia
f = fetch_filing(320193, "0000320193-25-000079")
sel = select_section(f)        # click the balance sheet in the browser
sel.facts                      # the resolved XBRL facts you picked
```
"""
function select_section(f::Filing; timeout::Real=1800, classify::Bool=false, opener=_open_in_default_app)
    sels = _run_picker(f; timeout, opener, multi=false)
    isempty(sels) &&
        error("select_section: no selection within $(timeout)s (cancelled or timed out)")
    sel = first(sels)
    classify && (sel = _classify_selection(sel, statement_map(f)))
    @info "select_section: captured" kind=sel.kind selector=sel.selector chars=length(sel.text) facts=length(sel.facts)
    return sel
end

"""
    select_sections(f::Filing; timeout=1800, classify=false, opener=_open_in_default_app) -> Vector{Selection}

Like [`select_section`](@ref), but capture **several** regions in one browser session:
each **Enter**/click adds the highlighted region (the toolbar shows a running count),
and **Esc** finishes and returns everything collected as a `Vector{Selection}`. Repeated
picks of the same element are de-duplicated by selector. Returns an empty vector if you
finish without capturing anything (so, unlike `select_section`, it does not throw on an
empty result). The `timeout`, `classify` and `opener` keywords behave as in `select_section`
(with `classify=true` the `*_pre.xml` is fetched once and applied to every selection).

```julia
f    = fetch_filing(104169, "0000104169-26-000102")
sels = select_sections(f)      # pick the income statement, balance sheet, … then Esc
length(sels)                   # how many you captured
```
"""
function select_sections(f::Filing; timeout::Real=1800, classify::Bool=false, opener=_open_in_default_app)
    sels = _run_picker(f; timeout, opener, multi=true)
    if classify && any(!isempty(s.facts) for s in sels)
        stmts = statement_map(f)
        sels = [_classify_selection(s, stmts) for s in sels]
    end
    @info "select_sections: captured $(length(sels)) selection(s)" kinds=Tuple(s.kind for s in sels)
    return sels
end
